/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_management_system;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class EditAssessmentParticipant extends javax.swing.JFrame {
    
    private ProjectManagerHomePage ProjectManagerHomePage;
    private String ID;
    
    
    public void setPMPageInstance(ProjectManagerHomePage PMhomePage) {
        this.ProjectManagerHomePage = PMhomePage;
    }
    
    public void refreshStudentTable(String IDNameInCoOfStudent) {
        DefaultTableModel model = (DefaultTableModel)tStudentList.getModel();
        model.setRowCount(0);
        String line;
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("src\\project_management_system\\database\\student.txt"));
            while ((line = br.readLine()) != null) {
                String[] record = line.split("\t");
                
                if (record[0].toLowerCase().startsWith(IDNameInCoOfStudent) || record[1].toLowerCase().startsWith(IDNameInCoOfStudent)|| record[3].toLowerCase().startsWith(IDNameInCoOfStudent)) {
                    String [] newRecord = new String[3];
                    //Skip IC, Password, Address
                    System.arraycopy(record, 0, newRecord, 0, 2);
                    System.arraycopy(record, 3, newRecord, 2, 1);
                    //Add the record to Table
                    model.addRow(newRecord);
                    }
                }
            br.close();
        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    public void refreshAddedStudentTable() {
        DefaultTableModel model = (DefaultTableModel)tAddedStudent.getModel();
        model.setRowCount(0);
        String line;
        String studentName = "";
        String studentID = "";
        String intake = "";
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("src\\project_management_system\\database\\assessment_student.txt"));
            while ((line = br.readLine()) != null) {
                String[] record = line.split("\t");

                if (record[0].equals(ID)) {
                    BufferedReader studentReader = new BufferedReader(new FileReader("src\\project_management_system\\database\\student.txt"));

                    String studentLine;
                    while ((studentLine = studentReader.readLine()) != null) {
                        String[] studentRecord = studentLine.split("\t");
                        if (studentRecord[0].equalsIgnoreCase(record[1])) {
                            studentID = studentRecord[0];
                            studentName = studentRecord[1];
                            intake = studentRecord[3];
                            break;
                        }
                    }
                    
                    
                    //Add the record to Table
                    model.addRow(new Object[]{studentID, studentName,intake});
                    }
                }
            br.close();
        } catch (Exception e) {
            e.getMessage();
        }
    }
    
   public void setRecordData(String ID) {
       this.ID = ID;
       tfID.setText(ID);
       refreshAddedStudentTable();
       
       
       
       
    }
    
   
    
    
    

    /**
     * Creates new form EditLecturerDetails
     */
    public EditAssessmentParticipant() {
        initComponents();
        refreshStudentTable("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tStudentList = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tAddedStudent = new javax.swing.JTable();
        bAddStudent = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tfSearchStudent = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ID:");

        tfID.setEnabled(false);

        tStudentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Intake Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tStudentList);

        tAddedStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Intake Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tAddedStudent);

        bAddStudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bAddStudent.setText("ADD<");
        bAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddStudentActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("REMOVE>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfSearchStudent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchStudentKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Search:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bAddStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(bAddStudent)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                        .addComponent(jScrollPane4)))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfSearchStudentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchStudentKeyReleased
        // TODO add your handling code here:
        refreshStudentTable(tfSearchStudent.getText().toLowerCase());
    }//GEN-LAST:event_tfSearchStudentKeyReleased

    private void bAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddStudentActionPerformed
        // TODO add your handling code here:
        if (tStudentList.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "No Selected Student");
        }
        else {
            String selectionID = tStudentList.getModel().getValueAt(tStudentList.getSelectedRow(), 0).toString();
            String selectionName = tStudentList.getModel().getValueAt(tStudentList.getSelectedRow(), 1).toString();
            String intakeCode = tStudentList.getModel().getValueAt(tStudentList.getSelectedRow(), 2).toString();
            String[] studentRecord = new String[]{selectionID, selectionName, intakeCode};
        
            TableModel dataModel = tAddedStudent.getModel();
            boolean isDuplicated = false;

            for (int row = 0; row < tAddedStudent.getRowCount(); row++) {
                if(studentRecord[0].equals(dataModel.getValueAt(row, 0))){
                    isDuplicated = true;
                    break;
                }
            }
            
            if(isDuplicated) {
            JOptionPane.showMessageDialog(null, "This student already be added");
            }
            else{
                DefaultTableModel model = (DefaultTableModel)tAddedStudent.getModel();
                model.addRow(studentRecord);

                try {

                    BufferedWriter writer = new BufferedWriter(new FileWriter("src\\project_management_system\\database\\assessment_student.txt", true));
                    System.out.println(tAddedStudent.getRowCount());
                    for (int row = 0; row < tAddedStudent.getRowCount(); row++) {

                        StringBuilder record = new StringBuilder();
                        //Write the information to the text file
                        record.append(tfID.getText() + "\t" + tAddedStudent.getValueAt(row, 0) + "\t"
                                + "NA" + "\t" + "NA" + "\t" + "NA" + "\t" + "NA" + "\t" + "NA" + "\t"
                                + "NA" + "\t" + "NA" + "\t" + "NA" + "\t" + "NA" + "\t" + "NA");
                        writer.write(record + "\n");
                    }
                    writer.close();
                } catch (Exception e) {
                    System.err.println(e.getMessage());
                }

                studentRecord = null;
            }
        }
    }//GEN-LAST:event_bAddStudentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tAddedStudent.getModel();
        int[] rows = tAddedStudent.getSelectedRows();
        
        String selectedID = tAddedStudent.getModel().getValueAt(tAddedStudent.getSelectedRow(), 0).toString();
        if (rows.length > 0) {
            for (int i = 0; i < rows.length; i++) {
                model.removeRow(rows[i] - i);
            }

            try {
                BufferedReader br = new BufferedReader(new FileReader("src\\project_management_system\\database\\assessment_student.txt"));
                String line;
                ArrayList<String[]> newRecord = new ArrayList<>();
                while ((line = br.readLine()) != null) {
                    String[] record = line.split("\t");
                    if (record[1].equals(selectedID) && record[0].equals(ID)) {
                        continue;
                    } else {
                        newRecord.add(record);
                    }

                }
                br.close();

                //Write the new lines to the text file
                BufferedWriter writer = new BufferedWriter(new FileWriter("src\\project_management_system\\database\\assessment_student.txt"));
                for (String[] record : newRecord) {
                    String lineToWrite = String.join("\t", record);
                    writer.write(lineToWrite);
                    writer.newLine();
                }

                writer.close();

            } catch (Exception e) {
                System.err.println(e.getMessage());
            }


            
        } else {
            JOptionPane.showMessageDialog(null, "No student be selected to removed!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAssessmentParticipant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAssessmentParticipant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAssessmentParticipant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAssessmentParticipant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAssessmentParticipant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddStudent;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tAddedStudent;
    private javax.swing.JTable tStudentList;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfSearchStudent;
    // End of variables declaration//GEN-END:variables
}
