/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project_Management_System;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.BorderFactory;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;


/**
 *
 * @author User
 */
public class LecturerAssessmentMarking1 extends javax.swing.JFrame {

      private String ID;

    /**
     * Creates new form LecturerAssessmentMarking1
     */
    public LecturerAssessmentMarking1() {
        initComponents();
    }

    public void setID(String ID) {
        this.ID = ID;
        createAssessmentPanels();
    }

    private void createAssessmentPanels() {
        firstMarkerAssessmentjPanel.removeAll();

        String line;
        String line2;
        int count = 0;

        try (BufferedReader br2 = new BufferedReader(new FileReader("src\\Project_Management_System\\database\\lecturer.txt"))) {
            while ((line2 = br2.readLine()) != null) {
                String[] record2 = line2.split("\t");
                try (BufferedReader br = new BufferedReader(new FileReader("src\\Project_Management_System\\database\\assessment.txt"))) {
                    while ((line = br.readLine()) != null) {
                        String[] record = line.split("\t");
                        System.out.println("Checking assessment: " + record[0] + " with lecturer ID: " + record[6]);

                        if (ID.equals(record[6])) {
                            
                            javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
                            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                            jPanel1.setLayout(jPanel1Layout);

                            javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
                            javax.swing.JLabel jLabel2 = new javax.swing.JLabel();

                            jLabel1.setText(record[0]);
                            jLabel2.setText(record[1]);

                            jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addContainerGap(100, Short.MAX_VALUE))
                            );
                            jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            );

                            jPanel1.setPreferredSize(new Dimension(450, 50));
                            jPanel1.setBorder(BorderFactory.createLineBorder(Color.black));
                            jPanel1.setCursor(new Cursor(Cursor.HAND_CURSOR));

                            jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
                                public void mouseReleased(java.awt.event.MouseEvent evt) {
                                    // Add your code for handling the click event here
                                }
                            });
                            firstMarkerAssessmentjPanel.add(jPanel1);
                           
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        firstMarkerAssessmentjPanel.setPreferredSize(new Dimension(350, count * 55));
        firstmarkerAssessment.setViewportView(firstMarkerAssessmentjPanel);
        firstMarkerAssessmentjPanel.revalidate();
        firstMarkerAssessmentjPanel.repaint();
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDashboard = new javax.swing.JPanel();
        mainTitleLabel = new javax.swing.JLabel();
        firstmarkerAssessment = new javax.swing.JScrollPane();
        firstMarkerAssessmentjPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pDashboard.setBackground(new java.awt.Color(252, 247, 204));
        pDashboard.setPreferredSize(new java.awt.Dimension(1500, 780));

        mainTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainTitleLabel.setText("Lecturer Assessment Marking");
        mainTitleLabel.setPreferredSize(new java.awt.Dimension(200, 160));

        firstmarkerAssessment.setViewportView(firstMarkerAssessmentjPanel);

        javax.swing.GroupLayout pDashboardLayout = new javax.swing.GroupLayout(pDashboard);
        pDashboard.setLayout(pDashboardLayout);
        pDashboardLayout.setHorizontalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstmarkerAssessment, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(604, 604, 604))
        );
        pDashboardLayout.setVerticalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(mainTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(firstmarkerAssessment, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 1576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerAssessmentMarking1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerAssessmentMarking1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerAssessmentMarking1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerAssessmentMarking1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerAssessmentMarking1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel firstMarkerAssessmentjPanel;
    private javax.swing.JScrollPane firstmarkerAssessment;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JPanel pDashboard;
    // End of variables declaration//GEN-END:variables
}
